global:
  scrape_interval: 5s

scrape_configs:
  - job_name: chatchat_web
    metrics_path: /metrics
    static_configs:
      - targets:
          - web:4000
  - job_name: chatchat_tcp
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - tcp
        type: A
        port: 9568
        refresh_interval: 5s
  - job_name: chatchat_tcp_local
    static_configs:
      - targets:
          - host.docker.internal:9568
  - job_name: haproxy
    metrics_path: /metrics
    static_configs:
      - targets:
          - haproxy:8404
